version: "3.3"

services:
  apache:
    image: httpd:latest
    container_name: apache
    hostname: apache
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.apache-rtr.entrypoints=https"
      - "traefik.http.routers.apache-rtr.rule=Host(`apache.jjsoft.io`)"
      - "traefik.http.routers.apache-rtr.tls=true"
      - "traefik.http.routers.apache-rtr.middlewares=chain-no-auth@file"
      - "traefik.http.routers.apache-rtr.service=apache-svc"
      - "traefik.http.services.apache-svc.loadbalancer.server.port=80"
    networks:
      - t2_proxy
networks:
  t2_proxy:
    external:
      name: t2_proxy