version: "3.3"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    hostname: nginx
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx-rtr.entrypoints=https"
      - "traefik.http.routers.nginx-rtr.rule=Host(`nginx.jjsoft.io`)"
      - "traefik.http.routers.nginx-rtr.tls=true"
      - "traefik.http.routers.nginx-rtr.middlewares=chain-no-auth@file"
      - "traefik.http.routers.nginx-rtr.service=nginx-svc"
      - "traefik.http.services.nginx-svc.loadbalancer.server.port=80"
    networks:
      - t2_proxy
networks:
  t2_proxy:
    external:
      name: t2_proxy