version: "3.3"

services:
  whoami:
    image: "containous/whoami"
    container_name: "whoami"
    hostname: "whoami"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami-rtr.entrypoints=https"
      - "traefik.http.routers.whoami-rtr.rule=Host(`whoami.jjsoft.io`)"
      - "traefik.http.routers.whoami-rtr.tls=true"
      - "traefik.http.routers.whoami-rtr.middlewares=chain-basic-auth@file"
      - "traefik.http.routers.whoami-rtr.service=whoami-svc"
      - "traefik.http.services.whoami-svc.loadbalancer.server.port=80"
    networks:
      - t2_proxy
networks:
  t2_proxy:
    external:
      name: t2_proxy